{
 "title": "TreeSQL",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Lookups & Scans",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "lookup_latency_ns_count" },
    { "expr": "scan_latency_ns_count" }
   ]
  },
  {
   "title": "Lookup Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "lookup_latency_ns" },
    {}
   ]
  },
  {
   "title": "Scan Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "scan_latency_ns" }
   ]
  },
  {
   "title": "Insert Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "insert_latency_ns" }
   ]
  },
  {
   "title": "Select Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "select_latency_ns" }
   ]
  },
  {
   "title": "Connections and Channels",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "open_connections" },
    { "expr": "open_channels" }
   ]
  },
  {
   "title": "Query Rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(insert_latency_ns_count[1m])"
    },
    {
     "expr": "rate(select_latency_ns_count[1m])"
    }
   ]
  },
  {
   "title": "Listeners",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "record_listeners" },
    { "expr": "whole_table_listeners" },
    { "expr": "filtered_table_listeners" }
   ]
  },
  {
   "title": "Next connection id",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "next_connection_id" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_virtual_memory_bytes" },
    { "expr": "process_resident_memory_bytes" }
   ]
  },
  {
   "title": "GCs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    { "expr": "go_gc_duration_seconds_count" }
   ]
  }
 ]
}