# deploy with `docker stack deploy slacker --compose-file slacker.dockerstack.yml`
version: '3'
services:
  grafana:
    image: 'grafana/grafana:latest'
    links:
      - prometheus
    ports:
      - '3000:3000'
  prometheus:
    image: 'vilterp/treesql-prometheus:latest'
    links:
      - treesql-server
    ports:
      - '9090:9090'
  treesql-server:
    image: 'vilterp/treesql:latest'
    ports:
      - '9000:9000'
    restart: always
    volumes:
      - '/mnt/treesql-data/slacker:/data'
  treesql-slacker:
    image: 'vilterp/treesql-slacker:latest'
    ports:
      - '80:8080'
  treesql-webui:
    image: 'vilterp/treesql-webui:latest'
    ports:
      - '9001:8080'
